# Site settings
title: Jieun S. Park
email: jpark2@cord.edu
description: >
 Department of Political Science
 Concordia College
 Moorhead, MN 56562
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jieunspark.github.io" # the base hostname & protocol for your site
github_username:  jieunspark
encoding: UTF-8
# Build settings
markdown: kramdown
